### ISSUE TITLE
License allows for inclusion in other projects?

### ISSUE THREAD

**Issue by brunorsch** [micaww/altv-rpc#15]
Hey Micah!

First things first, I want to praise you for your work in this lib, it fits perfectly my needs on RPC calls for my forthcoming server

Since it's a bit outdated, I found the need to modify some little things and to do so, I copied your code into my repo.

I then came to your Readme to look about any license or something, but could not find a thing. So I came here to ask: Can I copy your code and paste it into my server's codebase, given the following credits comment header?

```js
/**
 * CREDITS:
 * The code in this file is copied and adapted from Micah Allen's alt:V RPC library.
 * Source: https://github.com/micaww/altv-rpc
 * Thank you so much, Micah!
 */
```

I need to test if my changes didn't break anything, and after that, I may also make a PR if you think it's something interesting

Best regards

**Comment by micaww** [comment]
Hey, thanks! I appreciate the kind words 😊 

Please feel free to do whatever you want with this code! I have not touched GTAV in a couple of years and will probably not make any further changes to this library.
