### ISSUE TITLE
CEF to client doesn't work

### ISSUE THREAD

**Issue by xtance** [micaww/altv-rpc#5]
Works fine in RAGE:MP but not in AltV.
Nothing happens when rpc.callClient

Update: the fix is: `rpc.addWebView(browser);`  on clientside (as found in updated readme)

**Comment by micaww** [comment]
Hey @xtance do you have any reproducible example? I am using this heavily in a large project with no issues.

One major difference on this version as opposed to RageMP's implementation is that you have to specify a matching namespace in each context.

For example:

```ts
const rpc = require('altv-rpc');

rpc.init('myproject');

// now use it freely
rpc.callClient('blahblah').then(console.log);
```

**Comment by xtance** [comment]
Oops, sorry it's my bad, I forgot to add webview, probably that was the reason.
Can I re-use the same window.rpc after it was set like this? In other .js files in the same "browser"?

```
        <script src="./lib/altv-rpc-browser.js"></script>
        <script type="text/javascript">
            rpc.init('platee');
        </script>
```

**Comment by micaww** [comment]
No problem! Glad it worked :)

Yes of course, as long as all rpc calls happen _after_ the namespace has already been set, any file should be able to use that global `rpc` instance.

**Comment by xtance** [comment]
Nice, thanks for response and for this library. I'm going to close issue as the problem was resolved. :з
